{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vector-db.fullname" . }}
  labels: {{- include "vector-db.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "vector-db.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
